trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build_Backend
    jobs:
      - job: build_backend
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
          - script: |
              cd backend
              npm install
              npm run build || echo "No build script found"
          - script: |
              echo "Backend build complete"

  - stage: Build_Frontend
    dependsOn: Build_Backend
    jobs:
      - job: build_frontend
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
          - script: |
              cd frontend/cloud-front
              npm install
              npm run build
          - publish: frontend/cloud-front/dist
            artifact: frontend_dist