services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: vmeet-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - vmeet-network

  frontend:
    build:
      context: ./frontend/cloud-front
      dockerfile: Dockerfile.frontend
    container_name: vmeet-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    networks:
      - vmeet-network

networks:
  vmeet-network:
    driver: bridge
